name: Build and test

on: [push, pull_request]

jobs:

  windows-build:
    name: Build - Windows
    strategy:
      matrix:
        os: ['windows-2022']
        build_type: [Release]
        compiler: [{c: cl.exe, cxx: cl.exe}]
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install prerequisites
      run: python3 -m pip install -r third_party/requirements.txt

    - name: Install doxygen
      run: |
        choco install doxygen.install
        # The choco package doesn't update the PATH, so do that manually.
        Add-Content $env:GITHUB_PATH 'C:\Program Files\doxygen\bin'

    - name: Configure CMake
      run: >
        cmake
        -B${{github.workspace}}/build
        -DCMAKE_C_COMPILER=${{matrix.compiler.c}}
        -DCMAKE_CXX_COMPILER=${{matrix.compiler.cxx}}
        -DCMAKE_POLICY_DEFAULT_CMP0094=NEW
        -DUR_ENABLE_TRACING=ON
        -DUR_DEVELOPER_MODE=ON
        -DUR_BUILD_TESTS=ON
        -DUR_FORMAT_CPP_STYLE=ON

    - name: Generate source from spec, check for uncommitted diff
      if: matrix.os == 'windows-2022'
      run: cmake --build ${{github.workspace}}/build --target check-generated --config ${{matrix.build_type}}

    - name: Build all
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} -j 2

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build_type}} --output-on-failure -L "python|umf|loader|validation|tracing|unit|urtrace"

